{% set name = "uproot3-methods" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uproot3-methods-{{ version }}.tar.gz
  sha256: dd68f90be1ea276360b96369836849df29045f7fe4e534f9ac21ea00798ee358

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - awkward0
    - numpy >=1.13.1
    - python >={{ python_min }}

test:
  imports:
    - uproot3_methods
    - uproot3_methods.classes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scikit-hep/uproot3-methods
  summary: Pythonic mix-ins for ROOT classes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
